[PATCH 1/2] update-linux-headers.sh: add typelimits.h to portable
https://lore.kernel.org/qemu-devel/20260423012838.3695392-1-gaosong@loongson.cn

---

From: Song Gao <gaosong@loongson.cn>
To: qemu-devel@nongnu.org
Cc: maobibo@loongson.cn, philmd@linaro.org, richard.henderson@linaro.org,
 clg@redhat.com, pbonzini@redhat.com, cohuck@redhat.com, thuth@redhat.com,
 mst@redhat.com, peter.maydell@linaro.org
Subject: [PATCH 1/2] update-linux-headers.sh: add typelimits.h to portable
 header list
Date: Thu, 23 Apr 2026 09:28:37 +0800
Message-Id: <20260423012838.3695392-1-gaosong@loongson.cn>
X-Mailer: git-send-email 2.39.1
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
X-CM-TRANSID: qMiowJCx_8LQe+lpeAtzAA--.22398S2
X-CM-SenderInfo: 5jdr20tqj6z05rqj20fqof0/
X-Coremail-Antispam: 1Uk129KBjDUn29KB7ZKAUJUUUUU529EdanIXcx71UUUUU7KY7
 ZEXasCq-sGcSsGvfJ3UbIjqfuFe4nvWSU5nxnvy29KBjDU0xBIdaVrnUUvcSsGvfC2Kfnx
 nUUI43ZEXa7xR_UUUUUUUUU==
Received-SPF: pass client-ip=114.242.206.163; envelope-from=gaosong@loongson.cn;
 helo=mail.loongson.cn
X-Spam_score_int: -18
X-Spam_score: -1.9
X-Spam_bar: -
X-Spam_report: (-1.9 / 5.0 requ) BAYES_00=-1.9, SPF_HELO_NONE=0.001,
 SPF_PASS=-0.001 autolearn=ham autolearn_force=no
X-Spam_action: no action
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: qemu development <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org
Sender: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org

Linux kernel introduced a new UAPI header file typelimits.h in the 7.1
development cycle (commit merged in Jan 2026). This file is required by
ethtool.h and other headers that include it.

Since QEMU's update script only copies headers explicitly listed in the
for loop, typelimits.h was missing after updating to newer kernel
versions, causing compilation errors like:

  fatal error: standard-headers/linux/typelimits.h: No such file or directory

Add typelimits.h to the list of headers processed by cp_portable() to
ensure it is properly copied and sanitized into the QEMU source tree

Signed-off-by: Song Gao <gaosong@loongson.cn>
---
 scripts/update-linux-headers.sh | 1 +
 1 file changed, 1 insertion(+)

diff --git a/scripts/update-linux-headers.sh b/scripts/update-linux-headers.sh
index 386d7a38e7..471f9cc71e 100755
--- a/scripts/update-linux-headers.sh
+++ b/scripts/update-linux-headers.sh
@@ -255,6 +255,7 @@ for i in "$hdrdir"/include/linux/*virtio*.h \
          "$hdrdir/include/linux/vhost_types.h" \
          "$hdrdir/include/linux/vmclock-abi.h" \
          "$hdrdir/include/linux/nitro_enclaves.h" \
+         "$hdrdir/include/linux/typelimits.h" \
          "$hdrdir/include/linux/sysinfo.h"; do
     cp_portable "$i" "$output/include/standard-headers/linux"
 done
--
2.47.3

Signed-off-by: GitHub Actions Bot <bot@github.com>