target/ppc/kvm: Fix const violation when trimming CPU alias suffix
GCC 16 tightens diagnostics around const correctness and now correctly
rejects attempts to modify strings referenced through const-qualified
pointers. In kvm_ppc_register_host_cpu_type(), ppc_cpu_aliases[i].model
is defined as const char *, but the code was using strstr() on it and
then modifying the returned pointer in-place to strip
POWERPC_CPU_TYPE_SUFFIX.

This results in a write through a pointer derived from const data,
triggering a build failure with GCC 16:

  error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
        suffix = strstr(ppc_cpu_aliases[i].model, POWERPC_CPU_TYPE_SUFFIX);
               ^
Fix this by copying only the needed suffix from the object class-name to
'ppc_cpu_aliases.model' using g_strdup and g_strndup, which maintains the
constness of the allocated buffer assigned to 'ppc_cpu_aliases.model'
member of the 'ppc_cpu_aliases' struct array.

The patch also adds error handling for possible memory allocation failure
while calling g_str{n}dup functions so that the error is properly
propogated back from kvm_arch_init().

Signed-off-by: Amit Machhiwal <amachhiw@linux.ibm.com>
Signed-off-by: Vaibhav Jain (IBM) <vaibhav@linux.ibm.com>
Link: https://lore.kernel.org/qemu-devel/20260511131018.102168-1-vaibhav@linux.ibm.com