[PATCH] hw/scsi/vhost-scsi: fix build with older kernel headers
https://lore.kernel.org/qemu-devel/20260525182730.4098543-1-Quan.Sun@windriver.com

---

From: Quan.Sun@windriver.com
To: qemu-devel@nongnu.org
Cc: pbonzini@redhat.com, fam@euphon.net, mst@redhat.com, sgarzare@redhat.com,
 Quan.Sun@windriver.com
Subject: [PATCH] hw/scsi/vhost-scsi: fix build with older kernel headers
Date: Mon, 25 May 2026 11:27:30 -0700
Message-ID: <20260525182730.4098543-1-Quan.Sun@windriver.com>
X-Mailer: git-send-email 2.49.0
Content-Transfer-Encoding: 8bit
Content-Type: text/plain
X-ClientProxiedBy: SJ0PR03CA0094.namprd03.prod.outlook.com
 (2603:10b6:a03:333::9) To IA0PR11MB7283.namprd11.prod.outlook.com
 (2603:10b6:208:439::10)
MIME-Version: 1.0
X-MS-PublicTrafficType: Email
X-MS-TrafficTypeDiagnostic: IA0PR11MB7283:EE_|DM4PR11MB7304:EE_
X-MS-Office365-Filtering-Correlation-Id: 32fd48a3-cf37-4214-321f-08deba8b5256
X-MS-Exchange-SenderADCheck: 1
X-MS-Exchange-AntiSpam-Relay: 0
X-Microsoft-Antispam: BCL:0;
 ARA:13230040|366016|1800799024|376014|52116014|56012099003|18002099003|38350700014|11063799006;
X-Microsoft-Antispam-Message-Info: +GSC2BJRxQIUL4w6XxvWzdgWWHel0iGwj9OSnzTo+CzzVAVS7n2H4VIcN4vi5oHTLAWAqWaWn58F8231yYiMgDJjlB2+sM02mz2lXEucPAzAETthznYNbf5q0ybvAIAKcMs4KJlTN/k0tfwghSAv9DerQdMYqx5b2ZegKaO7yxBIdvKa7LG1BaS203eONdIL9XIciNWAr00adVvfm+Ji5ryuOj6PqbKNRbWogbcwVg7kVUpSbgJE4qiEXOq+MPirHRaKBZXe3KGgYZXuzJ9QEkjMxgnDPy09SWUxZT+XT1GnOgGnbvtyhREudr/flHWp0NYy5ufa/fxpBq+BB964nUHCKNW4Y3xgy+KJNQpF2Ki6Cgib2UQZxiwf0nQNRBPSqLIVMepKBaVh1vPZfiXhmcZhIZTbsDKUclaoEzuQtRL4ataJwwyGaYeiUO8vgcnFV/NO2Wn+EBUE4hRBE2NLDa/GIjs1AA3S6kXs5BWjUzhanLePTFm2hh9pbSZazGQhykbuthAksl9cTASb2MWJ5PnArSs3w2uP34KznfsWS2ZV37zIgGqFUWoYCnPcAbuXlg4PSWL/QJt0Aa5M7U/iCXo29oSYMCgGIxU8v5OXuN8S1h+yvUWCcLzTOC816ok3De7fBK7yhmbEc74GH7+06NVBYX4Ha6WzJOYIeNDyZp+go+SQb/uXxKgGzLLW6NUe8veFEpqURd0x8LMTvVGIN76g8SE68hSUTaxE8v7hpoY3qCAeHr0IsYiJayubydX6
X-Forefront-Antispam-Report: CIP:255.255.255.255; CTRY:; LANG:en; SCL:1; SRV:;
 IPV:NLI; SFV:NSPM; H:IA0PR11MB7283.namprd11.prod.outlook.com; PTR:; CAT:NONE;
 SFS:(13230040)(366016)(1800799024)(376014)(52116014)(56012099003)(18002099003)(38350700014)(11063799006);
 DIR:OUT; SFP:1101;
X-MS-Exchange-AntiSpam-MessageData-ChunkCount: 1
X-MS-Exchange-AntiSpam-MessageData-0: =?us-ascii?Q?/STb/s21hQFYaHtp+f+ECbHGwiY6Y4GPql6B1+nJscfmXBr9MAHNCKaf/MRk?=
 =?us-ascii?Q?x7sXsV333MyRmZusnAm6JcwgHBZORm0qHCdy8HnA0RGyay13corDDsBqbHQy?=
 =?us-ascii?Q?St/iHi4MW6jKb2XfElohzaX3ypOHGEG4B9Vf/+ut2jvhclavDI4lXQsM7RsE?=
 =?us-ascii?Q?YQlw9OCWDUEqAQrhM3c0g+2ObpMw5VPqtIdkM34tyUla2UvoNhvw/Fq7TPre?=
 =?us-ascii?Q?MR+43dsKHL3e6HMJKGj0qX6j9wITmBiKTNSE+eEdeEUdNRXUZN8VwiPhlyaF?=
 =?us-ascii?Q?ZU6CRW2ij42EuN8/1LMcG33raJCGa6VG0S9oG9IXXnaFVeltWXTus4sQYkhf?=
 =?us-ascii?Q?g+k1Grz8pi/8zPXyrXkMODXDW4os4wB5PUtIUIqgqHR+Jv7KZaLh+Ajb1KO7?=
 =?us-ascii?Q?8wa9tSEqecMh6PesKyjWRAP45YmQUkk+/sNGfILgCV/lp5MXm1ibjILyL5uh?=
 =?us-ascii?Q?dLPidCnfM8KR4UNlzX76TnkZi6YHpFCHTmwAsZDNyeeBH2b6mdO/dLXf3wcM?=
 =?us-ascii?Q?Jlp5n82lqlWyPQThgyiOSXuseRJ+PgAy+ZtvlsbOYSZMJsls5z+BFEzMwtsu?=
 =?us-ascii?Q?dvO5y0+LHxn1fAQ74NFaFmlB9WPeu5wUztee51oqs6oJ8LURso/LCndOnDSZ?=
 =?us-ascii?Q?+j2729ypIjroVL49aAXLPB6kxycDqe2jbGIhNoWYPJKCDdoqY6pUStVXBkdw?=
 =?us-ascii?Q?u4LoSSlKQoaaX4yV3DOP0URdnCIVL8XF/euiyDzoyvsTjuIKIawCEqQ0J1xA?=
 =?us-ascii?Q?+DMhPMosTF3wXDEXfWLak+6GhBARujICMaIY6foXFZP9xeQF5C8bj4t7Wv0X?=
 =?us-ascii?Q?iqawX/7j7jH8z2hUfdPDbRqmz6zoYHJdRPzKKYiA3COmkXT1K8RhIym+oo2j?=
 =?us-ascii?Q?3oUtK+u5kmyew1W2B6LtShRliZFLtPhZlUNYwSp3hjNajzgVjHvUhfZHhEsl?=
 =?us-ascii?Q?z1oLsy6IV2a27W5F1CHTtCkFt+f9AkUZwp5JcKbBzR1S96KSWg+ouclaifhh?=
 =?us-ascii?Q?Dm/zl2kkdsCYYA8YycItLM1HYwAjW8CJgvjBNhbrS4ISHW51qvqN5RZyhil3?=
 =?us-ascii?Q?5w2U8hpcVI4AOaW3A6ISjbOB6wRoLYeLvxUDnA4a6jbOaWmPUd1djualpYSM?=
 =?us-ascii?Q?B7w1hxzPsjAOaRztbCEmvqWbbSNOe4sSvF70EJ4VUlo/24bIK5MlH6Ilu7XV?=
 =?us-ascii?Q?6q1zFCkRxLOXiqxpKbz4r2AVH6ZuFFp/hh1u3zGJJbDRwzgq4f9mbMuyHqNO?=
 =?us-ascii?Q?apVxTuwzYc9SkxWWxkTHQG65ExIJkeC9RQ7bxkvnVopKmgGpvjr0PTyVzzum?=
 =?us-ascii?Q?LTqgIF7kaMmbccmau28U/TSzr4J4tmLktR9ln6V46G+FyTZcxsiJj9F3n8I3?=
 =?us-ascii?Q?KCeFRTioBmpfpTqXcHUEqMymNy3K+p3BNTVrr7naqSz/9gm73Puai/B0ocGc?=
 =?us-ascii?Q?FE/CxRWK+MwMnQsKWyn3qc5ZJ2TSEtyElKH5jcrf8scgylKM7NkTvqa1w6LP?=
 =?us-ascii?Q?VsPEUIBOSW3RkZbX93W+V1FUY9MjfEhjYi+yhHJTfdbpDTl7O1Vii3NnBEri?=
 =?us-ascii?Q?hCYLGhe7wcI8JaNvGA9JlJ3Xa/HxZd7UY4eT56cqR2wyo+QCqia2iKYlpvPD?=
 =?us-ascii?Q?uwuPVrydH/JJDbI9yDBkI36w+MT/JiwFjN1sPrsoE5fkp28xYWgF7ey8tjp5?=
 =?us-ascii?Q?pRzARwtGokRfLIzLxCfy3orUbwsTY9TW7g/cxFQGCuUnLKudnKKjJwSMvsbT?=
 =?us-ascii?Q?xpplBBy4/w=3D=3D?=
X-Exchange-RoutingPolicyChecked: p9mOH4ruLqCWYn1Zv1lwymrEDrX1yv1r1wu1esnYcLNtMM5jEoUac41Aq1n4TlT+8t2AjBpqmPUAsbzQMHvjGE4E2n0Kr6acA8NLpgZe/clSYnZ4hXQ7Fe0yvf5A/5s2tQYcQm0nktAq5J6InX7zOkuctcl5sKVanM4ciRResBudLkb0YZPiqdlj+1ZS6ICZbVNYMgJeyVURbtO8q+fRwHvWCDXDjCB+wZQSbfWU9CruFYtKrfixRRySheti3iclPOuZZvNcM9Rae54moMXZ8HgmZZg2QCbzyAOw7IF9DO7t1SJD6yC70nlucVfOIPcVoaY7HD0PvLhf9k+0UdyJQw==
X-OriginatorOrg: windriver.com
X-MS-Exchange-CrossTenant-Network-Message-Id: 32fd48a3-cf37-4214-321f-08deba8b5256
X-MS-Exchange-CrossTenant-AuthSource: IA0PR11MB7283.namprd11.prod.outlook.com
X-MS-Exchange-CrossTenant-AuthAs: Internal
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 25 May 2026 18:27:48.0773 (UTC)
X-MS-Exchange-CrossTenant-FromEntityHeader: Hosted
X-MS-Exchange-CrossTenant-Id: 8ddb2873-a1ad-4a18-ae4e-4644631433be
X-MS-Exchange-CrossTenant-MailboxType: HOSTED
X-MS-Exchange-CrossTenant-UserPrincipalName: iDLNSu+qaxDfi4kgjpk+0ez9/vuDN8Ui+/Cg8lJ1W/i4r3PnSOdxFmjDflln5dy7tfnTQZJp6xIbg1ghFy2KHg==
X-MS-Exchange-Transport-CrossTenantHeadersStamped: DM4PR11MB7304
X-Proofpoint-GUID: JfJ-eHmHuWNfI0l1c_NDjH4NIhcK7UdG
X-Proofpoint-Spam-Details-Enc: AW1haW4tMjYwNTI1MDE4NCBTYWx0ZWRfX20Qjr8+kjYVm
 Y4ceR2vWm2GUbhp0JGNURi54UEEpVTUyswIExgzyE0E8+U/uJSwcy0vslrU2PE/njLhsa5BmYyq
 +Otybqpyz7mgUYfoM+gIl1iu4YcPuDe4q8QWC0qUf2gkinyUzHq2yZjjz+hGWPG5tgw3FJaHVlc
 Tef01iHK649WZTNk7OAPr+vDyn9U/as/I89YQK0VXX+JMMW6VtFJ8r/7JpL+r6lljjNaqDk9rHD
 Bq3ZnL5f4lTG+fpeIrvv9J9suvAk21w9LEGU4Taly7KZ3dcbgAy7EPmR+AMjH0kj8XL9P5CW3zY
 XaGe3dGDva6ZaLsnXOXJna4DYJ8S0DjzWWfa+e+l3wMQneaqF0pJ5CQEla7JKMZMvsexkX/UaLv
 g+FT0L3OUZ76bsbrPHcBpo84FPjSSnpa3u31Zzeh7biDOhg4o45gqJGge3mBSa7M7njcY7J4BXB
 Qqle/TJANJ83YMy07aQ==
X-Authority-Analysis: v=2.4 cv=IMUyzAvG c=1 sm=1 tr=0 ts=6a1494a7 cx=c_pps
 a=MzitxtHdenuwXKuz6QWlPg==:117 a=6eWqkTHjU83fiwn7nKZWdM+Sl24=:19
 a=z/mQ4Ysz8XfWz/Q5cLBRGdckG28=:19 a=lCpzRmAYbLLaTzLvsPZ7Mbvzbb8=:19
 a=xqWC_Br6kY4A:10 a=NGcC8JguVDcA:10 a=VkNPw1HP01LnGYTKEx00:22
 a=bi6dqmuHe4P4UrxVR6um:22 a=iKiJcTA2PjBS6x5JeXcw:22 a=t7CeM3EgAAAA:8
 a=tOh3b7mK2cmqlCsdpQIA:9 a=FdTzh2GWekK77mhwV6Dw:22
X-Proofpoint-ORIG-GUID: JfJ-eHmHuWNfI0l1c_NDjH4NIhcK7UdG
X-Proofpoint-Virus-Version: vendor=baseguard
 engine=ICAP:2.0.293,Aquarius:18.0.1143,Hydra:6.1.51,FMLib:17.12.100.49
 definitions=2026-05-25_05,2026-05-18_01,2025-10-01_01
X-Proofpoint-Spam-Details: rule=outbound_notspam policy=outbound score=0
 spamscore=0 impostorscore=0 malwarescore=0 bulkscore=0 lowpriorityscore=0
 phishscore=0 priorityscore=1501 clxscore=1011 suspectscore=0 adultscore=0
 classifier=typeunknown authscore=0 authtc= authcc= route=outbound adjust=0
 reason=mlx scancount=1 engine=8.22.0-2605130000 definitions=main-2605250184
Received-SPF: pass client-ip=205.220.166.238;
 envelope-from=prvs=9605cd9704=quan.sun@windriver.com;
 helo=mx0a-0064b401.pphosted.com
X-Spam_score_int: -27
X-Spam_score: -2.8
X-Spam_bar: --
X-Spam_report: (-2.8 / 5.0 requ) BAYES_00=-1.9, DKIM_SIGNED=0.1,
 DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1,
 RCVD_IN_DNSWL_LOW=-0.7, RCVD_IN_MSPIKE_H2=0.001, SPF_HELO_NONE=0.001,
 T_SPF_TEMPERROR=0.01 autolearn=ham autolearn_force=no
X-Spam_action: no action
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: qemu development <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org
Sender: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org

From: Quan Sun <Quan.Sun@windriver.com>

On build hosts with kernel headers older than 6.0, the system's
<linux/vhost_types.h> does not define struct vhost_vring_worker or
struct vhost_worker_state, causing compilation of vhost-scsi.c to
fail:

  error: storage size of 'vq_worker' isn't known

Fix by including standard-headers/linux/vhost_types.h before the
system's <linux/vhost.h>, matching the existing pattern used in
hw/virtio/vhost-backend.c. QEMU's bundled header provides the
struct definitions, and its include guard prevents redefinition
when the system header pulls in its own vhost_types.h.

Signed-off-by: Quan Sun <Quan.Sun@windriver.com>
---
 hw/scsi/vhost-scsi.c | 1 +
 1 file changed, 1 insertion(+)

diff --git a/hw/scsi/vhost-scsi.c b/hw/scsi/vhost-scsi.c
index 699863cc10..10e8fbe503 100644
--- a/hw/scsi/vhost-scsi.c
+++ b/hw/scsi/vhost-scsi.c
@@ -15,6 +15,7 @@
  */

 #include "qemu/osdep.h"
+#include "standard-headers/linux/vhost_types.h"
 #include <linux/vhost.h>
 #include <sys/ioctl.h>
 #include "qapi/error.h"
--
2.43.0

Signed-off-by: GitHub Actions Bot <bot@github.com>