accel/kvm: Include missing 'exec/vaddr.h' and 'qemu/queue.h' headers
Commit b67be03e3ac ("accel/kvm: Widen pc/saved_insn for
kvm_sw_breakpoint") used the vaddr type in the kvm_sw_breakpoint
structure but forgot to include the header defining it. It is
however indirectly included via "cpu.h", which we want to remove.

The QTAILQ_ENTRY() macro is defined in "qemu/queue.h". Include
both headers in order to avoid later when refactoring unrelated
headers:

  include/system/kvm.h:398:5: error: expected specifier-qualifier-list before ‘QTAILQ_ENTRY’
    398 |     QTAILQ_ENTRY(kvm_sw_breakpoint) entry;
        |     ^~~~~~~~~~~~
  include/system/kvm.h:404:5: error: unknown type name 'vaddr'
    404 |     vaddr pc;
        |     ^~~~~
  include/system/kvm.h:405:5: error: unknown type name 'vaddr'
    405 |     vaddr saved_insn;
        |     ^~~~~

Reviewed-by: Alistair Francis <alistair.francis@wdc.com>
Signed-off-by: Philippe Mathieu-Daudé <philmd@linaro.org>
Link: https://lore.kernel.org/qemu-devel/20260402170434.94783-3-philmd@linaro.org