[PATCH 0/6] target/mips/tcg: MXU fixes and cleanups
https://lore.kernel.org/qemu-devel/20260914230901.1781309-1-richard.henderson@linaro.org

---

From: Richard Henderson <richard.henderson@linaro.org>
To: qemu-devel@nongnu.org
Cc: philmd@oss.qualcomm.com
Subject: [PATCH 0/6] target/mips/tcg: MXU fixes and cleanups
Date: Mon, 14 Sep 2026 13:08:52 -1000
Message-ID: <20260914230901.1781309-1-richard.henderson@linaro.org>
X-Mailer: git-send-email 2.53.0
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
Received-SPF: pass client-ip=2607:f8b0:4864:3b::10;
 envelope-from=richard.henderson@linaro.org; helo=mail-pz2-x10.google.com
X-Spam_score_int: -20
X-Spam_score: -2.1
X-Spam_bar: --
X-Spam_report: (-2.1 / 5.0 requ) BAYES_00=-1.9, DKIM_SIGNED=0.1,
 DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1,
 RCVD_IN_DNSWL_NONE=-0.0001, SPF_HELO_NONE=0.001,
 SPF_PASS=-0.001 autolearn=ham autolearn_force=no
X-Spam_action: no action
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: qemu development <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org
Sender: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org

Forthcoming tcg improvements will diagnose the passed null pointers,
with or without --enable-ubsan:

../src/target/mips/tcg/mxu_translate.c: In function ‘gen_mxu_S32MAX_S32MIN’:
../src/target/mips/tcg/mxu_translate.c:2149:13: error: argument 3 null where non-null expected [-Werror=nonnull]
 2149 |             tcg_gen_smax_i32(mxu_gpr[XRa - 1], mxu_gpr[XRx - 1], 0);
      |             ^~~~~~~~~~~~~~~~
In file included from /home/rth/qemu/src/include/tcg/tcg-op.h:11,
                 from ../src/target/mips/tcg/translate.h:12,
                 from ../src/target/mips/tcg/mxu_translate.c:19:
/home/rth/qemu/src/include/tcg/tcg-op-common.h:166:23: note: in a call to function ‘tcg_gen_smax_i32’ declared ‘nonnull’
  166 | QEMU_ARG_NONNULL void tcg_gen_smax_i32(TCGv_i32, TCGv_i32 arg1, TCGv_i32 arg2);
      |                       ^~~~~~~~~~~~~~~~
../src/target/mips/tcg/mxu_translate.c:2151:13: error: argument 3 null where non-null expected [-Werror=nonnull]
 2151 |             tcg_gen_smin_i32(mxu_gpr[XRa - 1], mxu_gpr[XRx - 1], 0);
      |             ^~~~~~~~~~~~~~~~
/home/rth/qemu/src/include/tcg/tcg-op-common.h:165:23: note: in a call to function ‘tcg_gen_smin_i32’ declared ‘nonnull’
  165 | QEMU_ARG_NONNULL void tcg_gen_smin_i32(TCGv_i32, TCGv_i32 arg1, TCGv_i32 arg2);
      |                       ^~~~~~~~~~~~~~~~
../src/target/mips/tcg/mxu_translate.c: In function ‘gen_mxu_d8sum’:
../src/target/mips/tcg/mxu_translate.c:3112:13: error: argument 2 null where non-null expected [-Werror=nonnull]
 3112 |             tcg_gen_mov_i32(t4, 0);
      |             ^~~~~~~~~~~~~~~
/home/rth/qemu/src/include/tcg/tcg-op-common.h:178:23: note: in a call to function ‘tcg_gen_mov_i32’ declared ‘nonnull’
  178 | QEMU_ARG_NONNULL void tcg_gen_mov_i32(TCGv_i32 ret, TCGv_i32 arg);
      |                       ^~~~~~~~~~~~~~~
../src/target/mips/tcg/mxu_translate.c:3123:13: error: argument 2 null where non-null expected [-Werror=nonnull]
 3123 |             tcg_gen_mov_i32(t5, 0);
      |             ^~~~~~~~~~~~~~~
/home/rth/qemu/src/include/tcg/tcg-op-common.h:178:23: note: in a call to function ‘tcg_gen_mov_i32’ declared ‘nonnull’
  178 | QEMU_ARG_NONNULL void tcg_gen_mov_i32(TCGv_i32 ret, TCGv_i32 arg);
      |                       ^~~~~~~~~~~~~~~

Mostly we need to drop all of the premature optimization vs
the zero register.  In the extremely unlikely event that zero
is passed, the optimizer will clean things up.

Split out a helper for 32-bit 3-operand insns, which fixes
the smin/smax failures above.

Quite a bit more work wants doing to clean up the 16- and 8-bit
3-operand insns, but except for the one instance in d8sum, those
aren't currently causing problems.

r~

Richard Henderson (6):
  target/mips/tcg: Fix zero in gen_mxu_d8sum
  target/mips/tcg: Drop zero optimization in gen_mxu_s32mul
  target/mips/tcg: Split out gen_mxu_logic
  target/mips/tcg: Use gen_mxu_logic for gen_mxu_S32MAX_S32MIN
  target/mips/tcg: Use gen_mxu_logic for gen_mxu_S32SLT
  target/mips/tcg: Use gen_mxu_logic for gen_mxu_S32CPS

 target/mips/tcg/mxu_translate.c | 265 +++++++-------------------------
 1 file changed, 59 insertions(+), 206 deletions(-)

--
2.53.0

Signed-off-by: GitHub Actions Bot <bot@github.com>