[PATCH] disas: Replace straggling CS_ARCH_SYSZ
https://lore.kernel.org/qemu-devel/20260824143033.306201-1-farman@linux.ibm.com

---

From: Eric Farman <farman@linux.ibm.com>
To: Richard Henderson <richard.henderson@linaro.org>,
 =?UTF-8?q?Philippe=20Mathieu-Daud=C3=A9?= <philmd@oss.qualcomm.com>
Cc: qemu-devel@nongnu.org, qemu-s390x@nongnu.org,
 Matthew Rosato <mjrosato@linux.ibm.com>, Eric Farman <farman@linux.ibm.com>
Subject: [PATCH] disas: Replace straggling CS_ARCH_SYSZ
Date: Mon, 24 Aug 2026 16:30:33 +0200
Message-ID: <20260824143033.306201-1-farman@linux.ibm.com>
X-Mailer: git-send-email 2.53.0
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
X-TM-AS-GCONF: 00
X-Authority-Analysis: v=2.4 cv=TfimcxQh c=1 sm=1 tr=0 ts=6a8c5592 cx=c_pps
 a=AfN7/Ok6k8XGzOShvHwTGQ==:117 a=AfN7/Ok6k8XGzOShvHwTGQ==:17
 a=IkcTkHD0fZMA:10 a=Sv0fKeRqtYgA:10 a=VkNPw1HP01LnGYTKEx00:22
 a=RnoormkPH1_aCDwRdu11:22 a=V8glGbnc2Ofi9Qvn3v5h:22 a=VnNF1IyMAAAA:8
 a=j-usCZypzy5qgyMhyvEA:9 a=QEXdDO2ut3YA:10
X-Proofpoint-Spam-Info: AW1haW4tMjYwODI0MDExOCBTYWx0ZWRfX9/DgE33ZGVfr
 YsKq66/VuswASvGWZGx8h+YINCNYhS/6xBsuVSArYOIiIWtomTBuiEC5mipms0WhvBtq+fZ2nbA
 oHIvhnAK1/2aEteN/lrfa7KxaAfToI8=
X-Proofpoint-GUID: AUGiyqFFoGzAksvfz82cwr69dyttPgJt
X-Proofpoint-ORIG-GUID: AUGiyqFFoGzAksvfz82cwr69dyttPgJt
X-Proofpoint-Spam-Details-Enc: AW1haW4tMjYwODI0MDExOCBTYWx0ZWRfX2zDGKrlWbrav
 0gW7GJemShq3Z0Ee7lZ5TWF/h+LXs9XqQY9fqlLh6tLbfcY9+2Fth6MRxRqX5t20mK8ZQdWwR6/
 cwQ7odAD8Ita6GetEkvaA2AKtwA+0350CXOGd3r6NaW7yrE+dLqgMqxFW7S0EXVIXO187UOp+h2
 PjsJMImSJmI+UIp3U56gpYYkMmKKlAQyJ1RiWrK6ooCw5+8HOy/I4RPwYFmwRFdmmG9NBb1L5Gk
 FRTmlmdG4mPdqr4C9qmdm4BAcYaHZx59hwoYbeFNp0anOjVzIja+jKI27z+Oa4GqTBWvT5xpDGa
 jhUBOV3DFrulG18B7yjYl6I2tn/D1x1wDw63TjuzUX7Fd8Py6ZlTCrzguAxaAiZhHo8yMriU0hc
 sAR5H8whgpNVeJB7cTixbtiP7Ph6yoWxRLaMpDrTwqBYqB5b+1IpqFYhZuoaQeFS7N51PywE4IU
 CYkuMQObWHp2X4EA0kg==
X-Proofpoint-Virus-Version: vendor=baseguard
 engine=ICAP:2.0.293,Aquarius:18.0.1176,Hydra:6.1.134,FMLib:17.12.100.49
 definitions=2026-08-24_04,2026-08-24_01,2025-10-01_01
X-Proofpoint-Spam-Details: rule=outbound_notspam policy=outbound score=0
 suspectscore=0 spamscore=0 bulkscore=0 malwarescore=0 priorityscore=1501
 lowpriorityscore=0 clxscore=1015 phishscore=0 impostorscore=0 adultscore=0
 classifier=typeunknown authscore=0 authtc= authcc= route=outbound adjust=0
 reason=mlx scancount=1 engine=8.22.0-2606150000 definitions=main-2608240118
Received-SPF: pass client-ip=148.163.158.5; envelope-from=farman@linux.ibm.com;
 helo=mx0b-001b2d01.pphosted.com
X-Spam_score_int: -26
X-Spam_score: -2.7
X-Spam_bar: --
X-Spam_report: (-2.7 / 5.0 requ) BAYES_00=-1.9, DKIM_SIGNED=0.1,
 DKIM_VALID=-0.1, DKIM_VALID_EF=-0.1, RCVD_IN_DNSWL_LOW=-0.7,
 RCVD_IN_MSPIKE_H3=0.001, RCVD_IN_MSPIKE_WL=0.001, SPF_HELO_NONE=0.001,
 SPF_PASS=-0.001 autolearn=ham autolearn_force=no
X-Spam_action: no action
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: qemu development <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org
Sender: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org

When updating to capstone v6, the define CS_ARCH_SYSZ was replaced
with CS_ARCH_SYSTEMZ, except here. On systems without capstone-devel
installed, this causes a compile error:

  ../disas/disas-host.c: In function =E2=80=98initialize_debug_host=E2=80=
=99:
  ../disas/disas-host.c:78:24: error: =E2=80=98CS_ARCH_SYSZ=E2=80=99 unde=
clared (first use in this function); did you mean =E2=80=98CS_ARCH_SH=E2=80=
=99?
     78 |     s->info.cap_arch =3D CS_ARCH_SYSZ;
        |                        ^~~~~~~~~~~~
        |                        CS_ARCH_SH
  ../disas/disas-host.c:78:24: note: each undeclared identifier is report=
ed only once for each function it appears in

Rather than making capstone required, replace the constant
with the same one used elsewhere after that change.

Fixes: c8220a096f ("target/s390x: Update capstone disassembly to v6")
Signed-off-by: Eric Farman <farman@linux.ibm.com>
---
 disas/disas-host.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/disas/disas-host.c b/disas/disas-host.c
index d41235250a..799f5e86c4 100644
--- a/disas/disas-host.c
+++ b/disas/disas-host.c
@@ -75,7 +75,7 @@ static void initialize_debug_host(CPUDebug *s)
 #elif defined(__m68k__)
     s->info.print_insn =3D print_insn_m68k;
 #elif defined(__s390x__)
-    s->info.cap_arch =3D CS_ARCH_SYSZ;
+    s->info.cap_arch =3D CS_ARCH_SYSTEMZ;
     s->info.cap_insn_unit =3D 2;
     s->info.cap_insn_split =3D 6;
 #elif defined(__hppa__)
--=20
2.53.0

Signed-off-by: GitHub Actions Bot <bot@github.com>