[PULL 0/5] Miscellaneous patches for 2026-05-05
https://lore.kernel.org/qemu-devel/20260505115036.1170186-1-armbru@redhat.com

---

From: Markus Armbruster <armbru@redhat.com>
To: qemu-devel@nongnu.org
Cc: stefanha@redhat.com
Subject: [PULL 0/5] Miscellaneous patches for 2026-05-05
Date: Tue,  5 May 2026 13:50:31 +0200
Message-ID: <20260505115036.1170186-1-armbru@redhat.com>
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Scanned-By: MIMEDefang 3.0 on 10.30.177.17
Received-SPF: pass client-ip=170.10.129.124; envelope-from=armbru@redhat.com;
 helo=us-smtp-delivery-124.mimecast.com
X-Spam_score_int: -24
X-Spam_score: -2.5
X-Spam_bar: --
X-Spam_report: (-2.5 / 5.0 requ) BAYES_00=-1.9, DKIMWL_WL_HIGH=-0.443,
 DKIM_SIGNED=0.1, DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1,
 RCVD_IN_DNSWL_NONE=-0.0001, RCVD_IN_MSPIKE_H4=0.001, RCVD_IN_MSPIKE_WL=0.001,
 SPF_HELO_PASS=-0.001, SPF_PASS=-0.001 autolearn=ham autolearn_force=no
X-Spam_action: no action
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: qemu development <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org
Sender: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org

The following changes since commit ac0cc20ad2fe0b8df2e5d9458e90a095ac711ab1:

  Merge tag 'for-upstream' of https://gitlab.com/bonzini/qemu into staging (2026-05-01 14:41:49 -0400)

are available in the Git repository at:

  https://repo.or.cz/qemu/armbru.git tags/pull-misc-2026-05-05

for you to fetch changes up to 8dc8f7b5bc755227c72eb74aa332e7a6bbb90066:

  qdev-monitor: Fix qdev ID validation regression (2026-05-05 12:52:26 +0200)

----------------------------------------------------------------
Miscellaneous patches for 2026-05-05

----------------------------------------------------------------
Markus Armbruster (5):
      hw/core: Deprecate query-kvm
      error: Fix "to current monitor if we have one" comments
      error: Restore error_printf()'s function comment
      qemu-print: Document qemu_fprintf(), qemu_vfprintf() failure
      qdev-monitor: Fix qdev ID validation regression

 docs/about/deprecated.rst |  5 +++++
 qapi/accelerator.json     |  8 +++++++-
 include/qapi/error.h      |  3 ++-
 system/qdev-monitor.c     | 12 ++++++++++--
 util/error-report.c       | 32 ++++++++++++++++++++++----------
 util/qemu-print.c         | 14 ++++++++++----
 6 files changed, 56 insertions(+), 18 deletions(-)

--
2.54.0

Signed-off-by: GitHub Actions Bot <bot@github.com>