tcg: Include missing 'qemu/bitops.h' header in tcg-gvec-desc.h
Include the missing 'qemu/bitops.h' header to avoid when refactoring
unrelated headers:

  In file included from target/arm/internals.h:34:
  include/tcg/tcg-gvec-desc.h:48:12: error: call to undeclared function 'extract32'
     48 |     return extract32(desc, SIMD_MAXSZ_SHIFT, SIMD_MAXSZ_BITS) * 8 + 8;
        |            ^

Signed-off-by: Philippe Mathieu-Daudé <philmd@oss.qualcomm.com>
Link: https://lore.kernel.org/qemu-devel/20260616153432.92939-2-philmd@oss.qualcomm.com