[PATCH] migration/vmstate: replace NULL pointer assert with proper
https://lore.kernel.org/qemu-devel/20260421155219.14506-1-viking4@gmail.com

---

From: Trieu Huynh <vikingtc4@gmail.com>
X-Google-Original-From: Trieu Huynh <viking4@gmail.com>
To: qemu-devel@nongnu.org
Cc: Trieu Huynh <vikingtc4@gmail.com>, Peter Xu <peterx@redhat.com>,
 Fabiano Rosas <farosas@suse.de>
Subject: [PATCH] migration/vmstate: replace NULL pointer assert with proper
 error
Date: Tue, 21 Apr 2026 22:52:19 +0700
Message-ID: <20260421155219.14506-1-viking4@gmail.com>
X-Mailer: git-send-email 2.43.0
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
Received-SPF: pass client-ip=2607:f8b0:4864:20::42a;
 envelope-from=vikingtc4@gmail.com; helo=mail-pf1-x42a.google.com
X-Spam_score_int: -17
X-Spam_score: -1.8
X-Spam_bar: -
X-Spam_report: (-1.8 / 5.0 requ) BAYES_00=-1.9, DKIM_SIGNED=0.1,
 DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1,
 FREEMAIL_ENVFROM_END_DIGIT=0.25, FREEMAIL_FROM=0.001,
 RCVD_IN_DNSWL_NONE=-0.0001, SPF_HELO_NONE=0.001,
 SPF_PASS=-0.001 autolearn=ham autolearn_force=no
X-Spam_action: no action
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: qemu development <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org
Sender: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org

From: Trieu Huynh <vikingtc4@gmail.com>

vmstate_load_state() contains an assert added in commit
("migration/vmstate: split up vmstate_base_addr" [1])
to catch NULL pointer dereferences early:

  assert(first_elem || !n_elems || !size);

However, the assert fires as an unrecoverable crash in a valid user
scenario, for instance: loading a snapshot saved with -icount auto
into a QEMU started without -icount. The "timer/icount/warp_timer"
subsection is present in the stream, but icount_warp_timer is NULL
because icount was never initialized. QEMU aborts with:

  qemu-system-x86_64: ../migration/vmstate.c:185:
  vmstate_load_state: Assertion `first_elem || !n_elems || !size'
  failed.

Replace the assert with a proper error_setg() and -EINVAL return so
QEMU reports a clear diagnostic instead of crashing.

Also remove the error_prepend() in vmstate_subsection_load() that
wrapped the error at each subsection level, producing a redundant and
noisy error chain. The original error message is now propagated as-is.

[1] https://lore.kernel.org/qemu-devel/20170228124056.5074-4-dgilbert@redhat.com/
Resolves: https://gitlab.com/qemu-project/qemu/-/work_items/2736

Signed-off-by: Trieu Huynh <vikingtc4@gmail.com>
---
Steps to reproduce:
* 1. Start src with icount config:
./qemu-system-x86_64 \
  -icount auto \
  -<other_options>

* 2. Save snapshot
(qemu) savevm snap1

* 3. Start dest without icount config:
./qemu-system-x86_64 \
  -<other_options>

* 4. Load snapshot
* As-is:
~ # QEMU 10.2.94 monitor - type 'help' for more information
(qemu) loadvm snap1
qemu-system-x86_64: ../migration/vmstate.c:185: vmstate_load_state:
Assertion `first_elem || !n_elems || !size' failed.
Aborted (core dumped)

* To-be:
** Before removing error_prepend()
~ # QEMU 10.2.94 monitor - type 'help' for more information
(qemu) loadvm snap1
Error: error while loading state for instance 0x0 of device 'timer':
Loading VM subsection 'timer/icount' in 'timer' failed: -22:
Loading VM subsection 'timer/icount/warp_timer' in 'timer/icount' failed: -22:
VM load of device 'timer/icount/warp_timer': field 'icount_warp_timer'
is a NULL pointer but snapshot contains data for it.

** After removing error_prepend()
~ # QEMU 10.2.94 monitor - type 'help' for more information
(qemu) loadvm snap1
Error: error while loading state for instance 0x0 of device 'timer':
VM load of device 'timer/icount/warp_timer': field 'icount_warp_timer'
is a NULL pointer but snapshot contains data for it.

 migration/vmstate.c | 11 +++++++----
 1 file changed, 7 insertions(+), 4 deletions(-)

diff --git a/migration/vmstate.c b/migration/vmstate.c
index 4d28364f7b..32ecc8ed35 100644
--- a/migration/vmstate.c
+++ b/migration/vmstate.c
@@ -182,7 +182,13 @@ int vmstate_load_state(QEMUFile *f, const VMStateDescription *vmsd,
             vmstate_handle_alloc(first_elem, field, opaque);
             if (field->flags & VMS_POINTER) {
                 first_elem = *(void **)first_elem;
-                assert(first_elem || !n_elems || !size);
+                if (!first_elem && n_elems && size) {
+                    error_setg(errp,
+                               "VM load of device '%s': field '%s' is a NULL "
+                               "pointer but snapshot contains data for it.",
+                               vmsd->name, field->name);
+                    return -EINVAL;
+                }
             }
             for (i = 0; i < n_elems; i++) {
                 void *curr_elem = first_elem + size * i;
@@ -651,9 +657,6 @@ static int vmstate_subsection_load(QEMUFile *f, const VMStateDescription *vmsd,
         ret = vmstate_load_state(f, sub_vmsd, opaque, version_id, errp);
         if (ret) {
             trace_vmstate_subsection_load_bad(vmsd->name, idstr, "(child)");
-            error_prepend(errp,
-                          "Loading VM subsection '%s' in '%s' failed: %d: ",
-                          idstr, vmsd->name, ret);
             return ret;
         }
     }
--
2.43.0

Signed-off-by: GitHub Actions Bot <bot@github.com>