qemu-img: fix warning when building with -fno-inline
ccache cc -m64 -Iqemu-img.p -I. -I.. -Iqapi -Itrace -Iui -Iui/shader -I/usr/include/uuid -I/usr/include/p11-kit-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -fdiagnostics-color=auto -Wall -Winvalid-pch -Werror -std=gnu11 -O2 -g -fstack-protector-strong -Wempty-body -Wendif-labels -Wexpansion-to-defined -Wformat-security -Wformat-y2k -Wignored-qualifiers -Wimplicit-fallthrough=2 -Winit-self -Wmissing-format-attribute -Wmissing-prototypes -Wnested-externs -Wold-style-declaration -Wold-style-definition -Wredundant-decls -Wshadow=local -Wstrict-prototypes -Wtype-limits -Wundef -Wvla -Wwrite-strings -Wno-missing-include-dirs -Wno-psabi -Wno-shift-negative-value -isystem /home/user/.work/qemu/linux-headers -isystem linux-headers -iquote . -iquote /home/user/.work/qemu -iquote /home/user/.work/qemu/include -iquote /home/user/.work/qemu/host/include/x86_64 -iquote /home/user/.work/qemu/host/include/generic -iquote /home/user/.work/qemu/tcg/i386 -pthread -mcx16 -msse2 -D_GNU_SOURCE -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-common -fwrapv -ftrivial-auto-var-init=zero -fzero-call-used-regs=used-gpr -fno-omit-frame-pointer -pg -fno-inline -fPIE -D_FILE_OFFSET_BITS=64 -D__USE_FILE_OFFSET64 -D__USE_LARGEFILE64 -DUSE_POSIX_ACLS=1 -MD -MQ qemu-img.p/qemu-img.c.o -MF qemu-img.p/qemu-img.c.o.d -o qemu-img.p/qemu-img.c.o -c ../qemu-img.c
/home/user/.work/qemu/qemu-img.c: In function ‘convert_co_do_copy’:
/home/user/.work/qemu/qemu-img.c:2006:20: error: ‘n’ may be used uninitialized [-Werror=maybe-uninitialized]
 2006 |             s->ret = n;
      |             ~~~~~~~^~~
/home/user/.work/qemu/qemu-img.c:1991:13: note: ‘n’ was declared here
 1991 |         int n;

Signed-off-by: Pierrick Bouvier <pierrick.bouvier@linaro.org>