hw/display: Guard new_blob to fix Wunused-function
The call to virtio_gpu_virgl_resource_new_blob() should be guarded like
the (sole) caller is, to avoid -Wunused-function.

        ../hw/display/virtio-gpu-virgl.c:328:1: error: ‘virtio_gpu_virgl_resource_new_blob’ defined but not used [-Werror=unused-function]
      328 | virtio_gpu_virgl_resource_new_blob(uint32_t resource_id, uint64_t blob_size)
          | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Brian Cain <brian.cain@oss.qualcomm.com>
Fixes: d814b44636d0 ("hw/display/virtio-gpu: introduce  virtio_gpu_{simple,virgl}_resource_new()")
Reviewed-by: Akihiko Odaki <odaki@rsg.ci.i.u-tokyo.ac.jp>
Reviewed-by: Brian Cain <brian.cain@oss.qualcomm.com>
Reviewed-by: Michael Tokarev <mjt@tls.msk.ru>
Link: https://lore.kernel.org/qemu-devel/20260911141906.736052-1-brian.cain@oss.qualcomm.com