accel/kvm: Include missing 'exec/cpu-common.h' header
kvm-all.c uses EXCP_INTERRUPT and EXCP_HLT, defined in the
"exec/cpu-common.h" header:

 17 #define EXCP_INTERRUPT  0x10000 /* async interruption */
 18 #define EXCP_HLT        0x10001 /* hlt instruction reached */

This header is indirectly included via "system/kvm.h" -> "cpu.h".
Since we want to remove the latter inclusion, include it here in
order to avoid otherwise:

  accel/kvm/kvm-all.c: In function 'kvm_handle_internal_error':
  accel/kvm/kvm-all.c:3147:20: error: 'EXCP_INTERRUPT' undeclared (first use in this function); did you mean 'SA_INTERRUPT'?
   3147 |             return EXCP_INTERRUPT;
        |                    ^~~~~~~~~~~~~~
  accel/kvm/kvm-all.c: In function 'kvm_cpu_exec':
  accel/kvm/kvm-all.c:3436:16: error: 'EXCP_HLT' undeclared (first use in this function)
   3436 |         return EXCP_HLT;
        |                ^~~~~~~~
  accel/kvm/kvm-all.c:3490:23: error: 'EXCP_INTERRUPT' undeclared (first use in this function); did you mean 'SA_INTERRUPT'?
   3490 |                 ret = EXCP_INTERRUPT;
        |                       ^~~~~~~~~~~~~~

Signed-off-by: Philippe Mathieu-Daudé <philmd@linaro.org>
Link: https://lore.kernel.org/qemu-devel/20260402170434.94783-2-philmd@linaro.org