Meson build fails with igvm enabled
https://lore.kernel.org/qemu-devel/CANo9s6=YV6Cyyn7m5LaGaD7U9i61OSZwMyiyLbmUk_xHO4s8vA@mail.gmail.com

---

From: Luigi Leonardi <leonardi@redhat.com>
Date: Tue, 3 Mar 2026 11:27:36 +0100
X-Gm-Features: AaiRm515MmO4KUkZZP0vUj89wvoH7cRb6GnsJ5XH4fDHCvhYrfcjCla5rGphNvM
Message-ID: <CANo9s6=YV6Cyyn7m5LaGaD7U9i61OSZwMyiyLbmUk_xHO4s8vA@mail.gmail.com>
Subject: Meson build fails with igvm enabled
To: qemu-devel@nongnu.org
Cc: Paolo Bonzini <pbonzini@redhat.com>, Gerd Hoffmann <kraxel@redhat.com>,
 Stefano Garzarella <sgarzare@redhat.com>, Oliver Steffen <osteffen@redhat.com>
Content-Type: text/plain; charset="UTF-8"
Received-SPF: pass client-ip=170.10.129.124; envelope-from=lleonard@redhat.com;
 helo=us-smtp-delivery-124.mimecast.com
X-Spam_score_int: -5
X-Spam_score: -0.6
X-Spam_bar: /
X-Spam_report: (-0.6 / 5.0 requ) BAYES_00=-1.9, DKIMWL_WL_HIGH=-0.001,
 DKIM_SIGNED=0.1, DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1,
 RCVD_IN_DNSWL_NONE=-0.0001, RCVD_IN_MSPIKE_H4=0.001, RCVD_IN_MSPIKE_WL=0.001,
 RCVD_IN_VALIDITY_RPBL_BLOCKED=0.968, RCVD_IN_VALIDITY_SAFE_BLOCKED=0.495,
 SPF_HELO_PASS=-0.001, SPF_PASS=-0.001 autolearn=no autolearn_force=no
X-Spam_action: no action
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: qemu development <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org
Sender: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org

Hi all,

I found a problem when trying to build QEMU with igvm enabled:
When igvm is not installed in a "canonical" path, the build system
cannot find the library.

To reproduce:

build igvm (latest upstream, as there were some problems with pkg-config).
PREFIX=$HOME/igvminst make -f igvm_c/Makefile install

This would result in igvm being installed in $HOME/igvminst

Then build QEMU
PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:$HOME/igvminst/lib64/pkgconfig/"
./configure --target-list=x86_64-softmmu --enable-igvm

ninja -C build

This fails with the following error:

In file included from ../stubs/igvm.c:15:
/root/qemu/include/system/igvm-internal.h:19:10: fatal error:
igvm/igvm.h: No such file or directory
   19 | #include <igvm/igvm.h>
      |          ^~~~~~~~~~~~~

IIUC the problem is that the stubs/igvm.c file uses the igvm header
via the "igvm-internal.h", but the library is not added as a
dependency in the meson config file.

I tried this change to meson, but it doesn't seem to work.

Not sure how to fix this.

Thanks,
Luigi

index 6ae478b..5ac4ae9 100644
--- a/stubs/meson.build
+++ b/stubs/meson.build
@@ -72,7 +72,8 @@ if have_system
   stub_ss.add(files('cmos.c'))
   stub_ss.add(files('fw_cfg.c'))
   if igvm.found()
-    stub_ss.add(files('igvm.c'))
+    stub_ss.add(igvm)
+    stub_ss.add(files('igvm.c'), igvm)
   endif
   stub_ss.add(files('kvm.c'))
   stub_ss.add(files('target-get-monitor-def.c'))
diff --git a/target/i386/meson.build b/target/i386/meson.build
index d385eaf..b20e2d6 100644
--- a/target/i386/meson.build
+++ b/target/i386/meson.build
@@ -27,7 +27,8 @@ i386_system_ss.add(files(
 i386_system_ss.add(when: 'CONFIG_SEV', if_true: files('sev.c'),
                                        if_false: files('sev-system-stub.c'))
 if igvm.found()
-  i386_system_ss.add(files('igvm.c'))
+  i386_system_ss.add(igvm)
+  i386_system_ss.add(files('igvm.c'), igvm)
 endif

 i386_user_ss = ss.source_set()

Signed-off-by: GitHub Actions Bot <bot@github.com>