[PATCH v2] target/ppc/kvm: Fix const violation when trimming CPU alias suffix
https://lore.kernel.org/qemu-devel/20260511131018.102168-1-vaibhav@linux.ibm.com

---

From: Vaibhav Jain <vaibhav@linux.ibm.com>
To: qemu-devel@nongnu.org, kvm-ppc@vger.kernel.org, qemu-ppc@nongnu.org
Cc: Vaibhav Jain <vaibhav@linux.ibm.com>,
        Amit Machhiwal <amachhiw@linux.ibm.com>,
        Chinmay Rath <rathc@linux.ibm.com>, Glenn Miles <milesg@linux.ibm.com>,
        Paolo Bonzini <pbonzini@redhat.com>,
        Shivaprasad G Bhat <sbhat@linux.ibm.com>,
        Harsh Prateek Bora <harshpb@linux.ibm.com>
Subject: [PATCH v2] target/ppc/kvm: Fix const violation when trimming CPU alias suffix
Date: Mon, 11 May 2026 18:40:16 +0530
Message-ID: <20260511131018.102168-1-vaibhav@linux.ibm.com>
X-Mailer: git-send-email 2.54.0
Precedence: bulk
X-Mailing-List: kvm-ppc@vger.kernel.org
List-Id: <kvm-ppc.vger.kernel.org>
List-Subscribe: <mailto:kvm-ppc+subscribe@vger.kernel.org>
List-Unsubscribe: <mailto:kvm-ppc+unsubscribe@vger.kernel.org>
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
X-TM-AS-GCONF: 00
X-Proofpoint-Spam-Details-Enc: AW1haW4tMjYwNTExMDE0NSBTYWx0ZWRfX6Tw6Qp5uZMvo
 iNxgcWZEatbE8J+A/FJpS3H0eyFTIq/yC10x8Dg9ewuWTwQHf68yWEmKy/1v/91uWAAC/U8io/9
 GgG1sZqGeFktMqqnmKOsUoSqISsETQn/FnZ+FeAvENKVRRiS6CsoRCaoOoRpLHayKFgBBnb1mKs
 U250W3/vTMv6yZ5W5whdbALAXFgOt/PjCNE6D+LlgtoKonH6o4/l7ps/eY+Gm/hYcKBMc83RS4w
 qFJGAkR6RuY9xOeu29x0oUfLvwn1TB843QRlqcZb9YxeLSJjZaI9sDear3hWPskqfkpXaJePiAg
 hPOCXQ3Utkl274C9PYRwlFsv7Tr7bQ/82EUS5d/njuYeBYSUdjmWIeZ3spDsP0cqr2kP5vy17Jg
 0QgOfAMFlbCdjwptz5SRNuD/z2Du8AE5JafrhcCD/GiZCAhkWrWPs7VqfFTezzUujlGce2LxDOT
 I5OW0tOEupaXQfZRdxg==
X-Proofpoint-GUID: 1vJvpab_VU8opN_HPgf23E4LvDnTdMID
X-Proofpoint-ORIG-GUID: 1vJvpab_VU8opN_HPgf23E4LvDnTdMID
X-Authority-Analysis: v=2.4 cv=CeQ4Irrl c=1 sm=1 tr=0 ts=6a01d54a cx=c_pps
 a=AfN7/Ok6k8XGzOShvHwTGQ==:117 a=AfN7/Ok6k8XGzOShvHwTGQ==:17
 a=NGcC8JguVDcA:10 a=VkNPw1HP01LnGYTKEx00:22 a=RnoormkPH1_aCDwRdu11:22
 a=iQ6ETzBq9ecOQQE5vZCe:22 a=VwQbUJbxAAAA:8 a=VnNF1IyMAAAA:8
 a=AeOTFisfVSLvIChBu_YA:9
X-Proofpoint-Virus-Version: vendor=baseguard
 engine=ICAP:2.0.293,Aquarius:18.0.1143,Hydra:6.1.51,FMLib:17.12.100.49
 definitions=2026-05-11_03,2026-05-08_02,2025-10-01_01
X-Proofpoint-Spam-Details: rule=outbound_notspam policy=outbound score=0
 impostorscore=0 clxscore=1011 adultscore=0 malwarescore=0 bulkscore=0
 priorityscore=1501 phishscore=0 spamscore=0 lowpriorityscore=0 suspectscore=0
 classifier=typeunknown authscore=0 authtc= authcc= route=outbound adjust=0
 reason=mlx scancount=1 engine=8.22.0-2604200000 definitions=main-2605110145

GCC 16 tightens diagnostics around const correctness and now correctly
rejects attempts to modify strings referenced through const-qualified
pointers. In kvm_ppc_register_host_cpu_type(), ppc_cpu_aliases[i].model
is defined as const char *, but the code was using strstr() on it and
then modifying the returned pointer in-place to strip
POWERPC_CPU_TYPE_SUFFIX.

This results in a write through a pointer derived from const data,
triggering a build failure with GCC 16:

  error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
        suffix = strstr(ppc_cpu_aliases[i].model, POWERPC_CPU_TYPE_SUFFIX);
               ^
Fix this by copying only the needed suffix from the object class-name to
'ppc_cpu_aliases.model' using g_strdup and g_strndup, which maintains the
constness of the allocated buffer assigned to 'ppc_cpu_aliases.model'
member of the 'ppc_cpu_aliases' struct array.

The patch also adds error handling for possible memory allocation failure
while calling g_str{n}dup functions so that the error is properly
propogated back from kvm_arch_init().

Signed-off-by: Amit Machhiwal <amachhiw@linux.ibm.com>
Signed-off-by: Vaibhav Jain (IBM) <vaibhav@linux.ibm.com>

---
Change-log:

v1->v2:
https://lore.kernel.org/all/20260504134344.38958-1-amachhiw@linux.ibm.com
* Avoid pointer aliasing
* Handle memory allocation failure error
---
 target/ppc/kvm.c | 18 ++++++++++--------
 1 file changed, 10 insertions(+), 8 deletions(-)

diff --git a/target/ppc/kvm.c b/target/ppc/kvm.c
index 25c28ad089..42cd4f4fff 100644
--- a/target/ppc/kvm.c
+++ b/target/ppc/kvm.c
@@ -170,9 +170,8 @@ int kvm_arch_init(MachineState *ms, KVMState *s)

     cap_rpt_invalidate = kvm_vm_check_extension(s, KVM_CAP_PPC_RPT_INVALIDATE);
     cap_ail_mode_3 = kvm_vm_check_extension(s, KVM_CAP_PPC_AIL_MODE_3);
-    kvm_ppc_register_host_cpu_type();

-    return 0;
+    return kvm_ppc_register_host_cpu_type();
 }

 int kvm_arch_irqchip_create(KVMState *s)
@@ -2654,14 +2653,17 @@ static int kvm_ppc_register_host_cpu_type(void)
     dc = DEVICE_CLASS(ppc_cpu_get_family_class(pvr_pcc));
     for (i = 0; ppc_cpu_aliases[i].alias != NULL; i++) {
         if (g_ascii_strcasecmp(ppc_cpu_aliases[i].alias, dc->desc) == 0) {
-            char *suffix;
+            const gchar *suffix, *cname = object_class_get_name(oc);
+
+            suffix = g_strstr_len(cname, -1, POWERPC_CPU_TYPE_SUFFIX);
+            ppc_cpu_aliases[i].model = unlikely(suffix) ?
+                g_strndup(cname, suffix - cname) : g_strdup(cname);

-            ppc_cpu_aliases[i].model = g_strdup(object_class_get_name(oc));
-            suffix = strstr(ppc_cpu_aliases[i].model, POWERPC_CPU_TYPE_SUFFIX);
-            if (suffix) {
-                *suffix = 0;
+            if (!ppc_cpu_aliases[i].model) {
+                return -ENOMEM;
+            } else {
+                return 0;
             }
-            break;
         }
     }

--
2.54.0

Signed-off-by: GitHub Actions Bot <bot@github.com>