gitlab-ci: Fix macOS build by using bison from homebrew
Since commit 6beec3bcdaa ("target/hexagon: add build config for
softmmu") we build the Hexagon target by default when system
emulation is selected. This commit introduced a hard dependency
on the 'bison' program for the idef parser. The binary provided
by Darwin is too old, and the build now fails:

  $ ../configure
  python determined to be '/opt/homebrew/bin/python3'
  C compiler for the host machine: clang (clang 17.0.0 "Apple clang version 17.0.0 (clang-1700.6.4.2)")
  Program bison found: NO found 2.3 but need: '>=3.0' (/usr/bin/bison)

  ../target/hexagon/meson.build:300:8: ERROR: Program 'bison' not found or not executable

  ERROR: meson setup failed

Since we use a lcitool generated vars file, we already install
'bison' from homebrew, but we don't have its path in our $PATH
variable. Add it to the macos.yml PATH_EXTRA variable which will
amend it to the global $PATH.

Fixes: 6beec3bcdaa ("target/hexagon: add build config for softmmu")
Signed-off-by: Philippe Mathieu-Daudé <philmd@oss.qualcomm.com>
output: ['@BASENAME@.tab.c', '@BASENAME@.tab.h'],
Link: https://lore.kernel.org/qemu-devel/20260706211336.11131-1-philmd@oss.qualcomm.com