[PATCH] hw/cxl: Check mailbox input length before copying payload
https://lore.kernel.org/qemu-devel/20260507113011.3674785-1-physicalmtea@gmail.com

---

From: Jia Jia <physicalmtea@gmail.com>
To: Jonathan Cameron <jonathan.cameron@huawei.com>
Cc: Fan Ni <nifan.cxl@gmail.com>, Fabiano Rosas <farosas@suse.de>,
 Laurent Vivier <lvivier@redhat.com>, Paolo Bonzini <pbonzini@redhat.com>,
 qemu-devel@nongnu.org, Jia Jia <physicalmtea@gmail.com>
Subject: [PATCH] hw/cxl: Check mailbox input length before copying payload
Date: Thu,  7 May 2026 19:30:11 +0800
Message-Id: <20260507113011.3674785-1-physicalmtea@gmail.com>
X-Mailer: git-send-email 2.34.1
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
Received-SPF: pass client-ip=2607:f8b0:4864:20::42e;
 envelope-from=physicalmtea@gmail.com; helo=mail-pf1-x42e.google.com
X-Spam_score_int: -20
X-Spam_score: -2.1
X-Spam_bar: --
X-Spam_report: (-2.1 / 5.0 requ) BAYES_00=-1.9, DKIM_SIGNED=0.1,
 DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1, FREEMAIL_FROM=0.001,
 RCVD_IN_DNSWL_NONE=-0.0001, SPF_HELO_NONE=0.001,
 SPF_PASS=-0.001 autolearn=ham autolearn_force=no
X-Spam_action: no action
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: qemu development <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org
Sender: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org

mailbox_reg_write() copies the guest mailbox payload with g_memdup2(pl,
len_in) before checking whether len_in exceeds cci->payload_max. len_in
comes straight from CXL_DEV_MAILBOX_CMD.LENGTH, so a guest can make QEMU
read past the mailbox payload buffer before the command is dispatched.

A cxl-switch-mailbox-cci reproducer trips ASan with:

  ERROR: AddressSanitizer: heap-buffer-overflow
  READ of size 1048575
      #0 __interceptor_memcpy
      #1 g_memdup2
      #2 g_memdup2_qemu ../include/glib-compat.h:99
      #3 mailbox_reg_write ../hw/cxl/cxl-device-utils.c:205

Reject requests larger than cci->payload_max before copying the payload
and return CXL_MBOX_INVALID_PAYLOAD_LENGTH instead.

Fixes: c9460561ed ("hw/cxl/mbox: Generalize the CCI command processing")
Resolves: https://gitlab.com/qemu-project/qemu/-/work_items/3478
Signed-off-by: Jia Jia <physicalmtea@gmail.com>

---
 hw/cxl/cxl-device-utils.c | 19 ++++++++++++-------
 1 file changed, 12 insertions(+), 7 deletions(-)

diff --git a/hw/cxl/cxl-device-utils.c b/hw/cxl/cxl-device-utils.c
index e150d74457..6560fb146d 100644
--- a/hw/cxl/cxl-device-utils.c
+++ b/hw/cxl/cxl-device-utils.c
@@ -202,14 +202,19 @@ static void mailbox_reg_write(void *opaque, hwaddr offset, uint64_t value,
         bool bg_started = false;
         int rc;

-        pl_in_copy = g_memdup2(pl, len_in);
-        if (len_in == 0 || pl_in_copy) {
-            /* Avoid stale data  - including from earlier cmds */
-            memset(pl, 0, CXL_MAILBOX_MAX_PAYLOAD_SIZE);
-            rc = cxl_process_cci_message(cci, cmd_set, cmd, len_in, pl_in_copy,
-                                         &len_out, pl, &bg_started);
+        if (len_in > cci->payload_max) {
+            rc = CXL_MBOX_INVALID_PAYLOAD_LENGTH;
         } else {
-            rc = CXL_MBOX_INTERNAL_ERROR;
+            pl_in_copy = g_memdup2(pl, len_in);
+            if (len_in == 0 || pl_in_copy) {
+                /* Avoid stale data  - including from earlier cmds */
+                memset(pl, 0, CXL_MAILBOX_MAX_PAYLOAD_SIZE);
+                rc = cxl_process_cci_message(cci, cmd_set, cmd, len_in,
+                                             pl_in_copy, &len_out, pl,
+                                             &bg_started);
+            } else {
+                rc = CXL_MBOX_INTERNAL_ERROR;
+            }
         }

         /* Set bg and the return code */
--
2.39.5

Signed-off-by: GitHub Actions Bot <bot@github.com>