tests/docker/docker.py: fix run command with $UID == 0
when running with uid 0 (like in nested container), podman run fails
sporadically with:
``
Error: preparing container ... for attach: container uses ID mappings ([]specs
.LinuxIDMapping{specs.LinuxIDMapping{ContainerID:0x3e9, HostID:0x0, Size:0x1}}), but doesn't map UID 0
```

Since default user in containers is 0 (run without -u option), there is
no need to repeat that in this case.

Signed-off-by: Pierrick Bouvier <pierrick.bouvier@oss.qualcomm.com>