[PATCH v2] target/ppc/kvm: Fix const violation when trimming CPU alias suffix
https://lore.kernel.org/qemu-devel/20260508081416.1014-1-amachhiw@linux.ibm.com

---

From: Amit Machhiwal <amachhiw@linux.ibm.com>
To: Harsh Prateek Bora <harshpb@linux.ibm.com>, qemu-ppc@nongnu.org
Cc: Vaibhav Jain <vaibhav@linux.ibm.com>,
        Amit Machhiwal <amachhiw@linux.ibm.com>,
        Chinmay Rath <rathc@linux.ibm.com>, Glenn Miles <milesg@linux.ibm.com>,
        Paolo Bonzini <pbonzini@redhat.com>,
        Nicholas Piggin <npiggin@gmail.com>, qemu-devel@nongnu.org,
        kvm@vger.kernel.org
Subject: [PATCH v2] target/ppc/kvm: Fix const violation when trimming CPU alias suffix
Date: Fri,  8 May 2026 13:44:16 +0530
Message-ID: <20260508081416.1014-1-amachhiw@linux.ibm.com>
X-Mailer: git-send-email 2.50.1
Precedence: bulk
X-Mailing-List: kvm@vger.kernel.org
List-Id: <kvm.vger.kernel.org>
List-Subscribe: <mailto:kvm+subscribe@vger.kernel.org>
List-Unsubscribe: <mailto:kvm+unsubscribe@vger.kernel.org>
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
X-TM-AS-GCONF: 00
X-Proofpoint-Reinject: loops=2 maxloops=12
X-Authority-Analysis: v=2.4 cv=XPQAjwhE c=1 sm=1 tr=0 ts=69fd9b68 cx=c_pps
 a=AfN7/Ok6k8XGzOShvHwTGQ==:117 a=AfN7/Ok6k8XGzOShvHwTGQ==:17
 a=NGcC8JguVDcA:10 a=VkNPw1HP01LnGYTKEx00:22 a=RnoormkPH1_aCDwRdu11:22
 a=Y2IxJ9c9Rs8Kov3niI8_:22 a=VnNF1IyMAAAA:8 a=AeOTFisfVSLvIChBu_YA:9
X-Proofpoint-ORIG-GUID: WaN1AC-txv3OxNEf3wjo66vUuO9DbVsf
X-Proofpoint-GUID: keBsE2Z7nBSFIVOlkCYr7Ezz-iXBpZYs
X-Proofpoint-Spam-Details-Enc: AW1haW4tMjYwNTA4MDA4MSBTYWx0ZWRfX25FqieNcQr7U
 nFzebQthH1e0+fhjg/oRlVTnf+vbVVCc54Q6OU2eHAFrWHGGZkO9vp3WSXWN/q2yiNhwccvNdO1
 C0pZXest/AXFYpOy0hqWm25LVwrKUGpI3nPNXD/YMMR5dnv77RtCWvcHIyc3X7Ir5KqrQoJYRfq
 cL2X8KCwBREX1oO5WS/iECv49VtkGPtsKpZiUZtovyCoRtx3wfiyVvjMKCTKANUpTy7kJwVqiM/
 QQhfEvo1//hhrGuImhCfSJzqf7/3uCrHcd0FDU+lVFTzM347F8ooMFUuafAl53VgZBwzIPaeof3
 LytYSRCl53s/kZmOcfdgkO8vHfI5A9ud3LM9ZY2uHn7xJ2srRO/LtbdWpoASjyao67ZT5DrvB4V
 FV+v6RWfefWJP0Wh3F0xIwJigL2nazFVjScJcQNRMEkkXi8CNtv0tpJkn4PonF7kCoZ8cGWonbb
 HNSgheyUeClEzkC13Kg==
X-Proofpoint-Virus-Version: vendor=baseguard
 engine=ICAP:2.0.293,Aquarius:18.0.1143,Hydra:6.1.51,FMLib:17.12.100.49
 definitions=2026-05-07_02,2026-05-06_01,2025-10-01_01
X-Proofpoint-Spam-Details: rule=outbound_notspam policy=outbound score=0
 bulkscore=0 lowpriorityscore=0 suspectscore=0 adultscore=0 spamscore=0
 priorityscore=1501 impostorscore=0 phishscore=0 malwarescore=0 clxscore=1015
 classifier=typeunknown authscore=0 authtc= authcc= route=outbound adjust=0
 reason=mlx scancount=1 engine=8.22.0-2604200000 definitions=main-2605080081

GCC 16 tightens diagnostics around const correctness and now correctly
rejects attempts to modify strings referenced through const-qualified
pointers. In kvm_ppc_register_host_cpu_type(), ppc_cpu_aliases[i].model
is declared as const char *, but the code was using strstr() on it and
then modifying the returned pointer in place to strip
POWERPC_CPU_TYPE_SUFFIX.

This results in a write through a pointer derived from const data,
triggering a build failure with GCC 16:

  error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
        suffix = strstr(ppc_cpu_aliases[i].model, POWERPC_CPU_TYPE_SUFFIX);
               ^

Fix this by duplicating the model string into a mutable buffer using
g_strdup(), trimming the suffix on that temporary buffer, and only then
storing it in the alias table.

This preserves the existing behavior while avoiding modification of
const data and ensures compatibility with newer compilers.

No functional change intended.

Signed-off-by: Amit Machhiwal <amachhiw@linux.ibm.com>
---
Changes in v2:
  * trim the duplicated buffer before assigning it to ppc_cpu_aliases[i].model
---

 target/ppc/kvm.c | 7 ++++---
 1 file changed, 4 insertions(+), 3 deletions(-)

diff --git a/target/ppc/kvm.c b/target/ppc/kvm.c
index 25c28ad089c6..c2843b1421cb 100644
--- a/target/ppc/kvm.c
+++ b/target/ppc/kvm.c
@@ -2654,13 +2654,14 @@ static int kvm_ppc_register_host_cpu_type(void)
     dc = DEVICE_CLASS(ppc_cpu_get_family_class(pvr_pcc));
     for (i = 0; ppc_cpu_aliases[i].alias != NULL; i++) {
         if (g_ascii_strcasecmp(ppc_cpu_aliases[i].alias, dc->desc) == 0) {
-            char *suffix;
+            char *model, *suffix;

-            ppc_cpu_aliases[i].model = g_strdup(object_class_get_name(oc));
-            suffix = strstr(ppc_cpu_aliases[i].model, POWERPC_CPU_TYPE_SUFFIX);
+            model = g_strdup(object_class_get_name(oc));
+            suffix = strstr(model, POWERPC_CPU_TYPE_SUFFIX);
             if (suffix) {
                 *suffix = 0;
             }
+            ppc_cpu_aliases[i].model = model;
             break;
         }
     }

base-commit: ee7eb612be8f8886d48c1d0c1f1c65e495138f83
--
2.50.1 (Apple Git-155)

Signed-off-by: GitHub Actions Bot <bot@github.com>